import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

const rubik = Rubik({
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800']
})

export const metadata: Metadata = {
  title: "Meia-entrada estudantil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <link rel="shortcut icon" href="assets/logo.png" type="image/x-icon" />
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
